Revert "Adds diveRsity package."
This reverts commit c1bda3fd94a32ba50d76fc91cde8ee8a45c78f0e.

It appears that one of the dependencies of diveRsity, the package huge,
fails to install without error. More specifically, it compiles and builds
fine but then fails to load. The error can be found in the following log:
https://registry.hub.docker.com/u/hlapp/rpopgen/build_id/48281/code/bv3gka73ja9vfmpxjdiobkd/

```
** preparing package for lazy loading

Error in unloadNamespace(package) :
  namespace ‘lattice’ is imported by ‘Matrix’ so cannot be unloaded

Error in library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc,  :
  Package ‘lattice’ version 0.20.31 cannot be unloaded

ERROR: lazy loading failed for package ‘huge’

* removing ‘/usr/local/lib/R/site-library/huge’

Error in install.packages(pkgs = f, lib = lib, repos = if (isMatchingFile(f)) NULL else rep,  :
  installation of package ‘huge’ had non-zero exit status
```